version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: jask
      POSTGRES_USER: jask
      POSTGRES_PASSWORD: jask_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jask"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  livekit:
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    volumes:
      - ./livekit.yaml:/livekit.yaml
    command: --config /livekit.yaml
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - LIVEKIT_KEYS=devkey: devsecret

volumes:
  postgres_data:
  redis_data:
